// Mock data for Capacity Connect prototype

export const mockUsers = {
  trainee: {
    id: "u1",
    name: "Priya Sharma",
    email: "priya@moes.gov.in",
    role: "trainee" as const,
    department: "Oceanography",
    designation: "Junior Scientist",
    avatar: "PS",
    skills: ["Python", "Data Analysis", "Remote Sensing", "GIS"],
    joinedAt: "2024-01-15",
    status: "approved" as const,
  },
  trainer: {
    id: "u2",
    name: "Dr. Rajesh Kumar",
    email: "rajesh@moes.gov.in",
    role: "trainer" as const,
    department: "Climate Science",
    designation: "Senior Scientist",
    avatar: "RK",
    skills: ["Machine Learning", "Climate Modeling", "Python", "R"],
    joinedAt: "2023-06-10",
    status: "approved" as const,
    verified: true,
  },
  admin: {
    id: "u3",
    name: "Anita Menon",
    email: "anita.admin@moes.gov.in",
    role: "admin" as const,
    department: "Administration",
    designation: "Platform Administrator",
    avatar: "AM",
    joinedAt: "2023-01-01",
    status: "approved" as const,
  },
};

export const mockCourses = [
  {
    id: "c1",
    title: "Introduction to Oceanography",
    description: "Explore the fundamentals of ocean science, including physical, chemical, biological and geological aspects of the world's oceans.",
    trainer: "Dr. Rajesh Kumar",
    trainerId: "u2",
    department: "Oceanography",
    tags: ["Ocean Science", "Marine Biology", "Fundamentals"],
    status: "published" as const,
    duration: "8 weeks",
    totalLessons: 24,
    enrolledCount: 142,
    rating: 4.7,
    thumbnail: "🌊",
    level: "Beginner",
    resources: [
      { id: "r1", type: "video", title: "Ocean Layers & Zones", duration: "45 min" },
      { id: "r2", type: "pdf", title: "Ocean Currents Study Guide", size: "2.4 MB" },
      { id: "r3", type: "video", title: "Marine Ecosystems", duration: "38 min" },
      { id: "r4", type: "slide", title: "Thermohaline Circulation", size: "5.1 MB" },
    ],
  },
  {
    id: "c2",
    title: "Climate Change & Earth Systems",
    description: "Understand the mechanisms of climate change, its impacts on Earth systems, and current scientific consensus on mitigation strategies.",
    trainer: "Dr. Ananya Pillai",
    trainerId: "u4",
    department: "Climate Science",
    tags: ["Climate Change", "Earth Systems", "Policy"],
    status: "published" as const,
    duration: "10 weeks",
    totalLessons: 30,
    enrolledCount: 289,
    rating: 4.9,
    thumbnail: "🌍",
    level: "Intermediate",
    resources: [
      { id: "r5", type: "video", title: "Greenhouse Effect Explained", duration: "52 min" },
      { id: "r6", type: "pdf", title: "IPCC Report Summary", size: "8.7 MB" },
      { id: "r7", type: "video", title: "Arctic Ice Melting", duration: "41 min" },
    ],
  },
  {
    id: "c3",
    title: "Remote Sensing & Satellite Data Analysis",
    description: "Learn to process and analyze satellite imagery for earth observation applications relevant to MoES research programs.",
    trainer: "Dr. Vikram Singh",
    trainerId: "u5",
    department: "Space Applications",
    tags: ["Remote Sensing", "GIS", "Satellite", "Data Analysis"],
    status: "published" as const,
    duration: "12 weeks",
    totalLessons: 36,
    enrolledCount: 98,
    rating: 4.6,
    thumbnail: "🛰️",
    level: "Advanced",
    resources: [
      { id: "r8", type: "video", title: "INSAT Data Processing", duration: "60 min" },
      { id: "r9", type: "pdf", title: "Remote Sensing Handbook", size: "12.3 MB" },
    ],
  },
  {
    id: "c4",
    title: "Earthquake Seismology",
    description: "Study seismic wave propagation, earthquake source mechanisms, and seismic hazard assessment methodologies.",
    trainer: "Dr. Meera Joshi",
    trainerId: "u6",
    department: "Seismology",
    tags: ["Seismology", "Earthquake", "Geophysics"],
    status: "published" as const,
    duration: "6 weeks",
    totalLessons: 18,
    enrolledCount: 67,
    rating: 4.5,
    thumbnail: "🌋",
    level: "Intermediate",
    resources: [],
  },
  {
    id: "c5",
    title: "Atmospheric Sciences Fundamentals",
    description: "Core principles of atmospheric physics, weather systems, and monsoon science relevant to Indian subcontinent.",
    trainer: "Dr. Rajesh Kumar",
    trainerId: "u2",
    department: "Atmospheric Sciences",
    tags: ["Atmosphere", "Weather", "Monsoon", "Physics"],
    status: "published" as const,
    duration: "8 weeks",
    totalLessons: 24,
    enrolledCount: 215,
    rating: 4.8,
    thumbnail: "☁️",
    level: "Beginner",
    resources: [],
  },
  {
    id: "c6",
    title: "Deep Sea Exploration Techniques",
    description: "Advanced methods for deep-sea research including ROV operations, pressure vessel design, and sample collection.",
    trainer: "Dr. Pradeep Nair",
    trainerId: "u7",
    department: "Deep Sea",
    tags: ["Deep Sea", "ROV", "Marine Technology"],
    status: "draft" as const,
    duration: "6 weeks",
    totalLessons: 20,
    enrolledCount: 0,
    rating: 0,
    thumbnail: "🔬",
    level: "Advanced",
    resources: [],
  },
];

export const mockEnrollments = [
  { courseId: "c1", progress: 65, status: "in_progress", completedAt: null },
  { courseId: "c2", progress: 100, status: "completed", completedAt: "2024-08-15" },
  { courseId: "c5", progress: 30, status: "in_progress", completedAt: null },
];

export const mockCertificates = [
  {
    id: "cert1",
    courseId: "c2",
    courseTitle: "Climate Change & Earth Systems",
    issuedAt: "2024-08-15",
    hash: "CC2024-A7F2-3B9E",
    validatedByAdmin: true,
  },
];

export const mockQuiz = {
  id: "q1",
  courseId: "c1",
  title: "Module 3: Ocean Currents Assessment",
  deadline: "2024-10-01T23:59:00",
  timeLimit: 30,
  questions: [
    {
      id: "qu1",
      text: "What drives thermohaline circulation in the ocean?",
      options: [
        { id: "o1", text: "Wind patterns only" },
        { id: "o2", text: "Differences in water temperature and salinity" },
        { id: "o3", text: "Tidal forces" },
        { id: "o4", text: "Solar radiation alone" },
      ],
      correctOption: "o2",
    },
    {
      id: "qu2",
      text: "The Indian Ocean Dipole primarily affects which region?",
      options: [
        { id: "o5", text: "North Atlantic" },
        { id: "o6", text: "Pacific Rim" },
        { id: "o7", text: "Monsoon rainfall over India and East Africa" },
        { id: "o8", text: "Arctic sea ice" },
      ],
      correctOption: "o7",
    },
    {
      id: "qu3",
      text: "Which layer of the ocean is characterized by a rapid temperature decrease with depth?",
      options: [
        { id: "o9", text: "Epipelagic zone" },
        { id: "o10", text: "Thermocline" },
        { id: "o11", text: "Abyssal zone" },
        { id: "o12", text: "Mesopelagic zone" },
      ],
      correctOption: "o10",
    },
    {
      id: "qu4",
      text: "What percentage of Earth's oxygen is produced by marine phytoplankton?",
      options: [
        { id: "o13", text: "20%" },
        { id: "o14", text: "50%" },
        { id: "o15", text: "70%" },
        { id: "o16", text: "90%" },
      ],
      correctOption: "o14",
    },
  ],
};

export const mockForumThreads = [
  {
    id: "t1",
    courseId: "c1",
    title: "Confused about thermohaline circulation direction in Southern Ocean",
    body: "I'm watching the lecture on deep water formation but I can't wrap my head around why AABW flows northward at depth. Can someone explain the pressure gradient logic?",
    author: "Priya Sharma",
    authorAvatar: "PS",
    isQuestion: true,
    acceptedReplyId: "rep2",
    upvotes: 12,
    createdAt: "2024-09-05T10:30:00",
    replies: [
      {
        id: "rep1",
        body: "Great question! The density differences are the key — AABW is the densest water mass in the ocean, formed by freezing seawater near Antarctica. Because it's denser, it sinks and then spreads northward along the ocean floor.",
        author: "Amit Verma",
        authorAvatar: "AV",
        isTrainer: false,
        upvotes: 8,
        createdAt: "2024-09-05T11:15:00",
      },
      {
        id: "rep2",
        body: "Think of it this way: water flows downhill. Dense water 'flows downhill' along the ocean floor. The Antarctic Bottom Water is formed at the surface near Antarctica (by brine rejection during sea ice formation), sinks immediately, and gravity pulls it along the seafloor toward the equator and beyond. The Coriolis effect then bends it slightly.",
        author: "Dr. Rajesh Kumar",
        authorAvatar: "RK",
        isTrainer: true,
        upvotes: 24,
        createdAt: "2024-09-05T14:00:00",
      },
    ],
  },
  {
    id: "t2",
    courseId: "c1",
    title: "Study group for Module 4 quiz — anyone interested?",
    body: "The deadline for the Ocean Currents quiz is Oct 1. I'm planning a virtual study session on Sep 28. DM me if interested!",
    author: "Rahul Desai",
    authorAvatar: "RD",
    isQuestion: false,
    acceptedReplyId: null,
    upvotes: 7,
    createdAt: "2024-09-10T09:00:00",
    replies: [
      {
        id: "rep3",
        body: "I'm in! What platform are we using?",
        author: "Sneha Patel",
        authorAvatar: "SP",
        isTrainer: false,
        upvotes: 2,
        createdAt: "2024-09-10T09:45:00",
      },
    ],
  },
];

export const mockAdminStats = {
  totalUsers: 1247,
  activeTrainees: 892,
  activeTrainers: 43,
  pendingApprovals: 17,
  totalCourses: 38,
  publishedCourses: 31,
  pendingCourses: 4,
  totalEnrollments: 4821,
  completionRate: 73,
  totalCertificates: 1204,
  pendingCertValidation: 8,
  monthlyEnrollments: [
    { month: "Apr", count: 320 },
    { month: "May", count: 415 },
    { month: "Jun", count: 380 },
    { month: "Jul", count: 490 },
    { month: "Aug", count: 560 },
    { month: "Sep", count: 620 },
  ],
  courseCompletionByDept: [
    { dept: "Oceanography", rate: 78 },
    { dept: "Climate Science", rate: 85 },
    { dept: "Seismology", rate: 62 },
    { dept: "Atmospheric", rate: 71 },
    { dept: "Deep Sea", rate: 55 },
  ],
  topCourses: [
    { title: "Climate Change & Earth Systems", enrollments: 289 },
    { title: "Atmospheric Sciences Fundamentals", enrollments: 215 },
    { title: "Introduction to Oceanography", enrollments: 142 },
    { title: "Remote Sensing & Satellite Data", enrollments: 98 },
    { title: "Earthquake Seismology", enrollments: 67 },
  ],
};

export const mockTrainerStats = {
  totalStudents: 357,
  avgRating: 4.75,
  totalCourses: 2,
  certificatesIssued: 203,
  quizScoreDistribution: [
    { range: "0-40%", count: 12 },
    { range: "41-60%", count: 34 },
    { range: "61-80%", count: 89 },
    { range: "81-100%", count: 157 },
  ],
  weeklyEngagement: [
    { week: "Week 1", views: 245, completions: 190 },
    { week: "Week 2", views: 310, completions: 220 },
    { week: "Week 3", views: 280, completions: 195 },
    { week: "Week 4", views: 350, completions: 265 },
    { week: "Week 5", views: 420, completions: 310 },
    { week: "Week 6", views: 390, completions: 285 },
  ],
  dropOffRates: [
    { lesson: "L1", retention: 100 },
    { lesson: "L2", retention: 92 },
    { lesson: "L3", retention: 85 },
    { lesson: "L4", retention: 79 },
    { lesson: "L5", retention: 72 },
    { lesson: "L6", retention: 68 },
    { lesson: "L7", retention: 65 },
    { lesson: "L8", retention: 61 },
  ],
};

export const mockPendingUsers = [
  { id: "pu1", name: "Karthik Nair", email: "karthik@moes.gov.in", role: "trainee", department: "Oceanography", appliedAt: "2024-09-08" },
  { id: "pu2", name: "Dr. Sunita Rao", email: "sunita@moes.gov.in", role: "trainer", department: "Climate Science", appliedAt: "2024-09-09", credentials: "PhD Climate Science, IIT Bombay" },
  { id: "pu3", name: "Mohan Gupta", email: "mohan@moes.gov.in", role: "trainee", department: "Atmospheric Sciences", appliedAt: "2024-09-10" },
  { id: "pu4", name: "Lakshmi Devi", email: "lakshmi@moes.gov.in", role: "trainee", department: "Seismology", appliedAt: "2024-09-10" },
  { id: "pu5", name: "Dr. Arjun Mehta", email: "arjun@moes.gov.in", role: "trainer", department: "Deep Sea Research", appliedAt: "2024-09-11", credentials: "MSc Marine Biology, CUSAT" },
];

export const mockCompetencyMap = [
  { trainer: "Dr. Rajesh Kumar", skills: ["Climate Modeling", "Python", "Machine Learning", "Atmospheric Science"], rating: 4.75, courses: 2 },
  { trainer: "Dr. Ananya Pillai", skills: ["Climate Change", "Policy Analysis", "IPCC", "GHG Accounting"], rating: 4.90, courses: 1 },
  { trainer: "Dr. Vikram Singh", skills: ["Remote Sensing", "GIS", "Satellite Data", "ISRO Tools"], rating: 4.60, courses: 1 },
  { trainer: "Dr. Meera Joshi", skills: ["Seismology", "Geophysics", "Earthquake Engineering"], rating: 4.50, courses: 1 },
  { trainer: "Dr. Pradeep Nair", skills: ["Deep Sea", "ROV Operations", "Marine Technology"], rating: 0, courses: 0 },
];

export const mockNotifications = [
  { id: "n1", type: "quiz", message: "Quiz deadline approaching: Ocean Currents Assessment due Oct 1", read: false, time: "2 hours ago" },
  { id: "n2", type: "reply", message: "Dr. Rajesh Kumar replied to your forum question", read: false, time: "5 hours ago" },
  { id: "n3", type: "certificate", message: "Your certificate for Climate Change & Earth Systems is ready", read: true, time: "2 days ago" },
  { id: "n4", type: "announcement", message: "New course: Deep Sea Exploration Techniques — coming soon!", read: true, time: "3 days ago" },
];

export const mockAnnouncements = [
  {
    id: "a1",
    type: "achievement",
    title: "MoES Training Milestone",
    body: "Over 1,200 certifications issued across all departments in FY 2024-25!",
    date: "2024-09-01",
    icon: "🏆",
  },
  {
    id: "a2",
    type: "announcement",
    title: "New Course: Deep Sea Exploration",
    body: "Enrollments open from October 15. Register early — limited seats available for field-staff cohort.",
    date: "2024-09-05",
    icon: "📢",
  },
  {
    id: "a3",
    type: "notification",
    title: "System Maintenance",
    body: "Scheduled downtime on Sep 20, 2:00 AM – 4:00 AM IST for database upgrades.",
    date: "2024-09-08",
    icon: "🔧",
  },
];

export const mockSkillGaps = [
  { skill: "Machine Learning", required: true, hasIt: false, courses: ["c2"] },
  { skill: "Python", required: true, hasIt: true, courses: [] },
  { skill: "Climate Modeling", required: true, hasIt: false, courses: ["c2"] },
  { skill: "Data Analysis", required: true, hasIt: true, courses: [] },
  { skill: "Remote Sensing", required: false, hasIt: false, courses: ["c3"] },
  { skill: "GIS", required: false, hasIt: true, courses: [] },
];
